//! Layout IR — the contract between the root crate (which converts cached
//! preview blocks into this IR) and the layout/emission engine in this crate.
//! Plain data only: no gpui types, no DOM, no markup strings.

/// A whole document to render: metadata, page options, block flow, and the
/// footnote bodies referenced from inline runs.
#[derive(Debug, Clone, Default)]
pub struct PdfDocument {
    pub metadata: PdfMetadata,
    pub options: PdfOptions,
    pub blocks: Vec<Block>,
    /// Footnote contents; the 1-based footnote id is the index + 1.
    pub footnotes: Vec<Vec<Run>>,
}

/// PDF document properties (title/author/date from YAML front matter).
#[derive(Debug, Clone, Default)]
pub struct PdfMetadata {
    pub title: Option<String>,
    pub author: Option<String>,
    pub date: Option<String>,
}

/// Page geometry and furniture options (from `[export.pdf]`).
#[derive(Debug, Clone, Copy, PartialEq)]
pub struct PdfOptions {
    pub page_width_mm: f32,
    pub page_height_mm: f32,
    /// Margin applied to all four sides, in millimetres.
    pub margin_mm: f32,
    /// Emit an opening table-of-contents page built from the headings.
    pub toc: bool,
    /// Draw a centered page-number footer.
    pub page_numbers: bool,
}

impl Default for PdfOptions {
    fn default() -> Self {
        Self {
            page_width_mm: 210.0,
            page_height_mm: 297.0,
            margin_mm: 25.0,
            toc: false,
            page_numbers: true,
        }
    }
}

/// One block-level element in document flow.
#[derive(Debug, Clone, PartialEq)]
pub enum Block {
    Heading { level: u8, content: Vec<Run> },
    Paragraph { content: Vec<Run> },
    /// `indent_level` is 0-based; the marker is generated by the writer.
    ListItem {
        indent_level: u8,
        marker: ListMarker,
        content: Vec<Run>,
    },
    Quote { children: Vec<Block> },
    Alert { kind: AlertKind, children: Vec<Block> },
    /// Pre-wrapped lines of styled runs; run colors carry syntax highlighting.
    CodeBlock {
        language: Option<String>,
        lines: Vec<Vec<Run>>,
    },
    Table {
        header: Vec<Cell>,
        rows: Vec<Vec<Cell>>,
        alignments: Vec<Alignment>,
    },
    Image {
        data: ImageData,
        alt: String,
        width_px: u32,
        height_px: u32,
    },
    Rule,
}

/// A table cell: inline content only.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Cell {
    pub content: Vec<Run>,
}

/// Generated list-item marker.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ListMarker {
    Bullet,
    /// The item's 1-based ordinal within its contiguous ordered list.
    Number(u64),
    Task { checked: bool },
}

/// GFM alert kinds.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AlertKind {
    Note,
    Tip,
    Important,
    Warning,
    Caution,
}

/// Column horizontal alignment.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Alignment {
    Left,
    Center,
    Right,
}

/// Embedded image payloads. SVG is emitted as vector graphics; PNG/JPEG keep
/// their compressed bytes.
#[derive(Debug, Clone, PartialEq)]
pub enum ImageData {
    Png(Vec<u8>),
    Jpeg(Vec<u8>),
    Svg(String),
}

/// One styled inline run.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Run {
    pub text: String,
    pub style: Style,
    /// External link target; renders underlined in the link color and gets a
    /// PDF link annotation.
    pub link: Option<String>,
    /// 1-based footnote id into [`PdfDocument::footnotes`]; the run text is
    /// replaced by a superscript reference number.
    pub footnote: Option<u32>,
}

/// Inline style flags. `color` carries syntax-highlight / accent colors
/// chosen by the root crate; `None` uses the default text color.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Style {
    pub bold: bool,
    pub italic: bool,
    pub strikethrough: bool,
    /// Marker-pen background behind the run.
    pub highlight: bool,
    pub superscript: bool,
    pub subscript: bool,
    /// Monospace stack.
    pub code: bool,
    pub color: Option<Rgb>,
}

/// 8-bit RGB color.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Rgb(pub u8, pub u8, pub u8);
